project_id = "ymyvzaqtiacgfknfuuwk"

[functions.send-verification-email]
verify_jwt = true

[functions.check-unverified-accounts]
verify_jwt = false

[functions.parse-job-description]
verify_jwt = true

[functions.parse-document]
verify_jwt = true

[functions.ai-assistant]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = false
